export const formInitialValues = {
  prefer_to_learn: "",
  prefer_learning_style: "",
  access_computer_and_net: "",
  solution_access_content: "",
  computer_skill_level: "",
  require_digital_resource: "",
  can_login_pc: "",
  can_send_mail: "",
  can_navigate_site: "",
  can_create_folder: "",
  can_find_info: "",
  can_attach_doc: "",
  can_save_mail: "",
  can_login_online_system: "",
  used_online_software: [],
  difficulties_in_learning: "",
  how_encounter_difficulities: "",
  study_techniques_in_past: "",
  best_way_to_learn: "",
  when_you_are_learning: "",
  prefer_presenter: "",
  support_to_complete_course: "",
  further_info_to_icv: "",
  further_info_description: "",
};
