export const formInitialValues = {
  unit_detail: "",
  building_name: "",
  street_number: "",
  street_name_and_type: "",
  suburb: "",
  state: "",
  post_code: "",
  postal_unit_detail: "",
  postal_building_name: "",
  postal_po_box: "",
  postal_street_number: "",
  postal_street_name_and_type: "",
  postal_suburb: "",
  postal_state: "",
  postal_post_code: "",
  home_phone: "",
  work_phone: "",
  mobile_no: "",
  email: "",
  contact_method: "",
  name: "",
  relationship: "",
  phone: "",
  mobile: "",
  same_as_redential: false,
};
