export const formInitialValues = {
  have_unique_identifier: "Yes",
  unique_identifier: "",
  create_usi: "Yes",
  contact_method: "",
  identified_contact_type: "Driver's Licence (Australian)",
  state: "",
  licence_number: "",
  expiry_month: "",
  expiry_year: "",
  card_name: "",
  card_no: "",
  refrence_no: "",
  card_color: "",
  document_no: "",
  passport_no: "",
  country_of_issue: "",
  birt_state: "",
  reg_no: "",
  date_printed: "",
  certificate_no: "",
  aquisition_date: "",
  stock_no: "",
  citizenship_aquisition_date: "",
  immi_card_no: "",
  have_victorian_stu_num: "",
  victorian_stu_num: "",
  usi_agreement: false,
};
